# kubectl --context gke-misc-prod apply -f manifest.yaml
kind: Namespace
apiVersion: v1
metadata:
  name: httpbin
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: httpbin
  name: httpbin
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        # docker build --tag eu.gcr.io/zeitonline-210413/httpbin:0.9.2-head .
        image: eu.gcr.io/zeitonline-210413/httpbin:0.9.2-head
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: httpbin
  name: httpbin-service
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: httpbin
  name: httpbin
  annotations:
    kubernetes.io/ingress.class: "nginx-fastly"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: "httpbin.ops.zeit.de"
    http:
      paths:
      - backend:
          serviceName: httpbin-service
          servicePort: 80
  tls:
  - hosts:
    - "httpbin.ops.zeit.de"
    secretName: tls-cert
