apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: europe-west3-docker.pkg.dev/zeitonline-engineering/docker-zon/httpbin
  newTag: 5abb87a3d39d5c384c66ec6d6106eaceb58554e5
