apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: europe-west3-docker.pkg.dev/zeitonline-engineering/docker-zon/httpbin
  newTag: c8025ff74b781ff2a2f439bbbedfa2952477533a
