name: Testrunner

on:
  pull_request:
  workflow_call: # triggered by ./release.yaml

env:
  project: httpbin

jobs:
  linter:
    uses: zeitonline/gh-action-workflows/.github/workflows/pre-commit.yaml@c59f973a7711502a6405ada24cbf2c2ee7db8dfb # 4.0.0
    with:
      python-version: "3.13"
      node-version: "24"
  k8s:
    uses: zeitonline/gh-action-workflows/.github/workflows/k8s-validation.yaml@c59f973a7711502a6405ada24cbf2c2ee7db8dfb # 4.0.0

  test:
    needs:
      - linter
      - k8s

    name: Test Run
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ZeitOnline/gh-action-baseproject@33c193b385a736184a1230cffe5ee5d1c9891da5 # v0.14.1
        id: baseproject
        with:
          project_name: ${{env.project}}
          environment: production
          setup_buildx: true
          google_auth: true
      - run: bin/test

      - uses: ZeitOnline/sysdig-scan-action@8e507758e02857ef6fa3ff1c1bb6871700d85de1 # v1.2.1
        with:
          gha_vault_role: ${{steps.baseproject.outputs.gha_vault_role}}
          image_tag: ${{secrets.GAR_DOCKER_REGISTRY}}/${{env.project}}:testing
