name: Testrunner

on:
  pull_request:
  workflow_call: # triggered by ./release.yaml

env:
  project: httpbin

jobs:
  linter:
    uses: zeitonline/gh-action-workflows/.github/workflows/pre-commit.yaml@c59f973a7711502a6405ada24cbf2c2ee7db8dfb # 4.0.0
    with:
      python-version: "3.13"
      node-version: "24"
  k8s:
    uses: zeitonline/gh-action-workflows/.github/workflows/k8s-validation.yaml@c59f973a7711502a6405ada24cbf2c2ee7db8dfb # 4.0.0

  test:
    needs:
      - linter
      - k8s

    name: Test Run
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ZeitOnline/gh-action-baseproject@33c193b385a736184a1230cffe5ee5d1c9891da5 # v0.14.1
        id: baseproject
        with:
          project_name: ${{env.project}}
          environment: production
          setup_buildx: true
          google_auth: true
      - run: bin/test

      - uses: ZeitOnline/sysdig-scan-action@67b45f2f91a3205a0876a45f89e3cd9d36c55c41 # v1.3
        with:
          gha_vault_role: ${{steps.baseproject.outputs.gha_vault_role}}
          image_tag: ${{secrets.GAR_DOCKER_REGISTRY}}/${{env.project}}:testing
